name: Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress documentation
        run: npm run docs:build

      - name: Build TypeDoc API documentation
        run: npm run typedoc:build

      - name: Copy TypeDoc to VitePress output
        run: |
          mkdir -p docs/.vitepress/dist/api-docs
          cp -r docs-api/* docs/.vitepress/dist/api-docs/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          cname: false
